import { Fredoka } from 'next/font/google'
import localFont from "next/font/local";
import "./globals.css";
import ReduxProvider from "@/components/Redux/ReduxProvider";

const Fredokas = Fredoka({  subsets: ['latin'] })



export const metadata = {
  title: "WAHID AHMED | FULL STACK DEVELOPER",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body  className={`${Fredokas.className} antialiased`} >
        <ReduxProvider >
           {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
